openapi: 3.0.3
info:
  title: Microcredential API
  description: Microcredential microservice API
  version: 1.0.0

paths:
  /microcredentials:
    $ref: './paths/microcredentials.yaml'
  /microcredentials/course/{courseId}:
    $ref: './paths/microcredentials-course-id.yaml'
  /microcredentials/{microcredentialId}:
    $ref: './paths/microcredentials-id.yaml'
  /microcredentials/{microcredentialId}/approve:
    $ref: './paths/microcredentials-id-approve.yaml'
  /microcredentials/{microcredentialId}/reject:
    $ref: './paths/microcredentials-id-reject.yaml'
  /microcredentials/pending:
    $ref: './paths/microcredentials-pending.yaml'

components:
  schemas:
    Error:
      $ref: './components/models/Error.yaml'

  responses:
    400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
